spring:
  application:
    name: browser-scheduler
  security:
    user:
      name: user
server:
  port: 8080
management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: '/actuator'
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: when-authorized
    env:
      show-values: when-authorized
    configprops:
      show-values: when-authorized
    shutdown:
      enabled: false

browser-scheduler:
  instanceName: BrowserSchedulerDefault
  gui:
    enable: true
    clearLogInterval: 43200
  browser:
    type: firefox
    maxTask: 1
    pageLoadStrategy: none
    headless: true
  jobParallelism: 1
  springComponentScanBasePackages: ""
  jobs:
  - name: RestartBrowser1
    enable: true
    impl: org.kquiet.browserscheduler.impl.common.RestartBrowser
    start: "2022-01-01T00:00:00"
    end: "2022-12-31T00:00:00"
    dailyStart: "23:00:00"
    dailyEnd: "23:00:00"
    interval: 43200
    scheduleAfterExec: true
    parameters:
      abc: "def"
  - name: RestartBrowser2
    enable: false
    impl: org.kquiet.browserscheduler.impl.common.RestartBrowser
    dailyStart: "05:00:00"
    dailyEnd: "05:00:01"
    interval: 43200
    scheduleAfterExec: true
    parameters:
      def: "ghi"
