# Create a custom Java runtime
#FROM eclipse-temurin:17.0.5_8-jdk-focal as jre-build
#RUN jlink --add-modules java.base,java.desktop,java.logging,java.management,java.datatransfer,java.prefs,java.xml --strip-debug --no-man-pages --no-header-files --compress=2 --output /javaruntime

#FROM ubuntu:focal-20221019
#ENV JAVA_HOME=/opt/java/openjdk
#ENV PATH "${JAVA_HOME}/bin:${PATH}"
#COPY --from=jre-build /javaruntime $JAVA_HOME

FROM eclipse-temurin:17.0.5_8-jre-focal
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
 && apt-get install -y --no-install-recommends ca-certificates wget curl unzip vim gnupg fonts-noto-cjk \
 && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
 && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list \
 && apt-get update && apt-get install -y --no-install-recommends google-chrome-stable \
 && CHROME_VERSION=`google-chrome-stable --version`;CHROME_FULL_VERSION=${CHROME_VERSION%%.*};CHROME_MAJOR_VERSION=`echo $CHROME_FULL_VERSION|sed "s/[^0-9]//g"` \
 && export CHROMEDRIVER_VERSION=`curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_MAJOR_VERSION%%.*}` \
 && curl -s -L -O "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" \
 && unzip chromedriver_linux64.zip && chmod +x chromedriver && mv chromedriver /usr/local/bin && rm chromedriver_linux64.zip \
 && apt-get install -y --no-install-recommends firefox firefox-geckodriver \
 && mkdir -p /opt/kquiet/job-scheduler/ext \
 && useradd -U kquiet -m -s /bin/bash \
 && chown -R kquiet:kquiet /opt/kquiet/

WORKDIR /opt/kquiet/${project.artifactId}

COPY --chown=kquiet:kquiet ["jobscheduler.sh", "./"]

COPY --chown=kquiet:kquiet ["${project.build.finalName}.jar", "lib", "logback.xml", "./lib/"]

USER kquiet:kquiet

ENTRYPOINT ["./jobscheduler.sh"]
